# Generated by Django 3.2.14 on 2023-08-21 11:39

import comapany.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_master',
            },
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('emp', models.ForeignKey(on_delete=models.SET(comapany.models.get_supervior_name), to='comapany.employee')),
            ],
            options={
                'db_table': 'address_master',
            },
        ),
    ]
